version: '3.3'

services:

  master:
    container_name: rlog_master
    image: rlog
    build:
      context: .
      dockerfile: Dockerfile
    volumes: []
    environment:
      PORT: 8080
      role: master # secondary
    command: |
      python3 /app/src/main.py -r master
    # bash -c '
    #   set -x
    #   supervisord -c /app/supervisord.conf
    # '
    networks:
      - default
    ports:
      - 8080:8080

  secondary1:
    container_name: rlog_secondary1
    image: rlog
    depends_on:
      - master
    build:
      context: .
      dockerfile: Dockerfile
    volumes: []
    environment:
      PORT: 8081
      ROLE: secondary # secondary master

    command: |
      python3 /app/src/main.py -r secondary -m http://master:8080 --port 8081
    # bash -c '
    #   set -x
    #   supervisord -c /app/supervisord.conf
    # '
    networks:
      - default
    ports:
      - 8081:8081


  # secondary2:
  #   container_name: rlog_secondary2
  #   image: rlog
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes: []
  #   environment:
  #     PORT: 8082
  #     ROLE: secondary # secondary master

  #   command: |
  #     python3 /app/src/main.py -r secondary -m http://master:8080 --port 8082
  #   # bash -c '
  #   #   set -x
  #   #   supervisord -c /app/supervisord.conf
  #   # '
  #   networks:
  #     - default
  #   ports:
  #     - 8082:8082


networks:
  default:
