version: '3.3'

services:

  master:
    image: rlog
    build:
      context: .
      dockerfile: Dockerfile
    volumes: []
    environment:
      PORT: 8080
    command: |
      python3 /app/src/main.py -u http://master:8080 --port 8080
    networks:
      - default
    ports:
      - 8080:8080

  secondary1:
    image: rlog
    depends_on:
      - master
    build:
      context: .
      dockerfile: Dockerfile
    volumes: []
    environment:
      PORT: 8081
    command: |
      python /app/src/main.py --port 8081 -u http://secondary1:8081 -m http://master:8080
    networks:
      - default
    ports:
      - 8081:8081

  secondary2:
    image: rlog
    depends_on:
      - master    
    build:
      context: .
      dockerfile: Dockerfile
    volumes: []
    environment:
      PORT: 8082
      ROLE: secondary # secondary master

    command: |
      python /app/src/main.py --port 8082 -u http://secondary2:8082 -m http://master:8080
    networks:
      - default
    ports:
      - 8082:8082


networks:
  default:
